create table if not exists public.vagas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  titulo text not null,
  area text not null,
  tipo text not null default 'Presencial',
  descricao text not null,
  requisitos text,
  status text not null default 'aberta'
);

alter table public.curriculos
  add column if not exists vaga_id bigint references public.vagas(id) on delete set null,
  add column if not exists vaga_titulo text;

create index if not exists vagas_status_created_at_idx
  on public.vagas (status, created_at desc);

create index if not exists curriculos_vaga_id_created_at_idx
  on public.curriculos (vaga_id, created_at desc);

alter table public.vagas enable row level security;

grant select, insert, update, delete on public.vagas to anon, authenticated;
grant usage, select on sequence public.vagas_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Vagas podem ser lidas'
  ) then
    create policy "Vagas podem ser lidas"
      on public.vagas
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico cria vagas'
  ) then
    create policy "Painel publico cria vagas"
      on public.vagas
      for insert
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico atualiza vagas'
  ) then
    create policy "Painel publico atualiza vagas"
      on public.vagas
      for update
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico exclui vagas'
  ) then
    create policy "Painel publico exclui vagas"
      on public.vagas
      for delete
      using (true);
  end if;
end $$;

notify pgrst, 'reload schema';
