create table if not exists public.vagas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  titulo text not null,
  area text not null,
  tipo text not null default 'Presencial',
  descricao text not null,
  requisitos text,
  status text not null default 'aberta'
);

alter table public.curriculos
  add column if not exists vaga_id bigint references public.vagas(id) on delete set null,
  add column if not exists vaga_titulo text;

create index if not exists vagas_status_created_at_idx
  on public.vagas (status, created_at desc);

create index if not exists curriculos_vaga_id_created_at_idx
  on public.curriculos (vaga_id, created_at desc);

do $$
declare
  constraint_record record;
  index_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.curriculos'::regclass
      and contype = 'u'
      and conkey = array[
        (
          select attnum
          from pg_attribute
          where attrelid = 'public.curriculos'::regclass
            and attname = 'cpf'
        )
      ]
  loop
    execute format('alter table public.curriculos drop constraint if exists %I', constraint_record.conname);
  end loop;

  for index_record in
    select indexname
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'curriculos'
      and indexdef ilike '%unique%'
      and indexdef ilike '%(cpf)%'
  loop
    execute format('drop index if exists public.%I', index_record.indexname);
  end loop;
end $$;

create unique index if not exists curriculos_cpf_vaga_id_unique_idx
  on public.curriculos (cpf, vaga_id)
  where vaga_id is not null;

alter table public.vagas enable row level security;

grant select, insert, update, delete on public.vagas to anon, authenticated;
grant usage, select on sequence public.vagas_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Vagas podem ser lidas'
  ) then
    create policy "Vagas podem ser lidas"
      on public.vagas
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico cria vagas'
  ) then
    create policy "Painel publico cria vagas"
      on public.vagas
      for insert
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico atualiza vagas'
  ) then
    create policy "Painel publico atualiza vagas"
      on public.vagas
      for update
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vagas' and policyname = 'Painel publico exclui vagas'
  ) then
    create policy "Painel publico exclui vagas"
      on public.vagas
      for delete
      using (true);
  end if;
end $$;

notify pgrst, 'reload schema';
